Feature-Engineering

1.Univariate Feature Selection

In [1]:
from pandas import read_csv
from numpy import set_printoptions
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2

In [2]:
filename = 'pima-indians-diabetes.data.csv'

In [3]:
names = ['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']

In [4]:
dataframe = read_csv(filename, names = names)

In [5]:
array = dataframe.values

In [6]:
x = array[:,0:8]
y = array[:,8]

In [7]:
# Feature Extraction
test = SelectKBest(score_func = chi2, k =4)
fit = test.fit(x,y)

In [8]:
# Summerize Score
set_printoptions(precision = 3)
print(fit.scores_)

[ 111.52  1411.887   17.605   53.108 2175.565  127.669    5.393  181.304]


In [9]:
features = fit.transform(x)
features

array([[148. ,   0. ,  33.6,  50. ],
       [ 85. ,   0. ,  26.6,  31. ],
       [183. ,   0. ,  23.3,  32. ],
       ...,
       [121. , 112. ,  26.2,  30. ],
       [126. ,   0. ,  30.1,  47. ],
       [ 93. ,   0. ,  30.4,  23. ]])

In [10]:
dataframe

preg  plas  pres  skin  test  mass   pedi  age  class
0       6   148    72    35     0  33.6  0.627   50      1
1       1    85    66    29     0  26.6  0.351   31      0
2       8   183    64     0     0  23.3  0.672   32      1
3       1    89    66    23    94  28.1  0.167   21      0
4       0   137    40    35   168  43.1  2.288   33      1
..    ...   ...   ...   ...   ...   ...    ...  ...    ...
763    10   101    76    48   180  32.9  0.171   63      0
764     2   122    70    27     0  36.8  0.340   27      0
765     5   121    72    23   112  26.2  0.245   30      0
766     1   126    60     0     0  30.1  0.349   47      1
767     1    93    70    31     0  30.4  0.315   23      0

[768 rows x 9 columns]

2.Recursive Feature Elimination

In [11]:
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression

In [12]:
# Load Data
filename = 'pima-indians-diabetes.data.csv'
names = ['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']

In [13]:
dataframe = read_csv(filename, names = names)

In [14]:
array = dataframe.values

In [15]:
x = array[:,0:8]
y = array[:,8]

In [16]:
# Feature Etraction
model = LogisticRegression(max_iter = 300)
rfe = RFE(model, 3)
fit = rfe.fit(x, y)

In [17]:
# Num Features:
fit.n_features_

3

In [18]:
# Selected Features:
fit.support_

array([ True, False, False, False, False,  True,  True, False])

In [19]:
# Feature Ranking:
fit.ranking_

array([1, 2, 4, 6, 5, 1, 1, 3])

3.Feature Importance Using Decision Tree

In [20]:
from sklearn.tree import DecisionTreeClassifier

In [21]:
# Load Data
filename = 'pima-indians-diabetes.data.csv'
names = ['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']

In [22]:
dataframe = read_csv(filename, names = names)

In [23]:
array = dataframe.values

In [24]:
x = array[:,0:8]
y = array[:,8]

In [25]:
# Feature Extraction
model = DecisionTreeClassifier()
model.fit(x, y)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [26]:
model.feature_importances_

array([0.057, 0.336, 0.087, 0.015, 0.046, 0.219, 0.128, 0.112])